#include <stdio.h>
#include <stdlib.h>

/* 
	CONFECICONAR UN PROGRAMA QUE PUEDA INGRESAR DIVERSOS VALOR  NUMERICOS QUE 
	CORRESPONDE A TEMPERATURAS MENORES A 99.99 GRADOS, MEDIDAS EN GRADOS 
	CENTIGRADOS, QUE FINALIZAN CON UNO QUE TIENE EL VALOR 99.99. 
	
	SE PIDE DETERMINAR E INFORMA: 
	A) EL VALOR MAYOR DETECTADO. 
	B) EL VALOR MENOR DETECTADO. 
	C) UNA LISTA CON LOS VALORES INGRESADOS EXPRESADOS EN GRADOS CENTIGRADOS Y 
		EN GRADOS FAHRENHEIT  (F = C/0.555 + 32).
*/

extern void exercise_28() {
	printf("\t\t***************************\n");
	printf("\t\t**      EJERCICIO 28     **\n");
	printf("\t\t***************************\n\n");
	
	
}
