#include <stdio.h>
#include <stdlib.h>

/* 
	SE PONEN A LA VENTA LAS ENTRADAS PARA UN PARTIDO DE FÚTBOL INTERNACIONAL, 
	CUYO PRECIO DEPENDE DE LA TRIBUNA, ASÍ: TRIBUNA  NORTE Y SUR CUESTAN 250 
	PESOS, TRIBUNA ORIENTE CUESTA  450 PESOS  Y TRIBUNA OCCIDENTE CUESTA  650 
	PESOS. 
	
	DISEÑE LA SOLUCIÓN EN UN PROGRAMA QUE CONTROLE LA VENTA DE DICHAS ENTRADAS A FIN DE PODER SABER LA CANTIDAD DE PERSONAS QUE ASISTEN A CADA TRIBUNA, LA CANTIDAD TOTAL DE PERSONAS Y EL MONTO TOTAL RECAUDADO POR LA VENTA DE TODAS LAS ENTRADAS. FINALIZA LA VENTA DE ENTRADAS CUANDO SE INGRESA UNA VENTA A TRIBUNA  IGUAL A "ZZZ".

*/

extern void exercise_27() {
	printf("\t\t***************************\n");
	printf("\t\t**      EJERCICIO 27     **\n");
	printf("\t\t***************************\n\n");
	
	
}
