#include <stdio.h>
#include <stdlib.h>

/* 
	UN NEGOCIO DE PERFUMERÍA EFECTÚA DESCUENTOS EN SUS VENTAS SEGÚN EL IMPORTE 
	DE ESTAS, CON LA SIGUIENTE ESCALA:
		MENOR  A 50 PESOS EL 3.5%
		ENTRE 50 Y 150 PESOS EL 10%
		ENTRE 151 Y 300 PESOS EL 20%
		MAYOR A 300 PESOS EL 25%

	CONFECCIONAR UN PROGRAMA QUE SOLICITE UN PRECIO ORIGINAL E INFORME: 
		EL DESCUENTO A EFECTUAR Y PRECIO NETO A COBRAR CON MENSAJES ACLARATORIOS. 
		SE DEBE CONTEMPLAR QUE SE PUEDE INGRESAR VARIOS IMPORTES Y PARA 
		FINALIZAR SE INGRESA UN VALOR NEGATIVO.      

*/

extern void exercise_24() {
	printf("\t\t***************************\n");
	printf("\t\t**      EJERCICIO 24     **\n");
	printf("\t\t***************************\n\n");
	
	
}
