#include <stdio.h>
#include <stdlib.h>

/* 
	UNA CEREALERA  DESEA CLASIFICAR SUS CLIENTES DE ACUERDO A LAS TONELADAS QUE 
	LE COMPRAN.

	CLIENTE QUE COMPRA MENOS DE 100 TONELADAS: CHICO.
	CLIENTE QUE COMPRA ENTRE 100 Y 300 TONELADAS: MEDIANO.
	CLIENTE QUE COMPRA MÁS DE 300 TONELADAS: GRANDE.
	
	SE DESEA DISEÑAR UN ALGORITMO QUE PERMITA EL INGRESO DE LAS TONELADAS POR 
	CLIENTE. FINALIZA EL INGRESO DE DATOS CUANDO SE INGRESE UN CLIENTE IGUAL A 
	000.
	
	LUEGO MUESTRE LA SIGUIENTE INFORMACIÓN POR PANTALLA: CANTIDAD DE CLIENTES, 
	PROMEDIO DE TONELADAS VENDIDAS POR CATEGORÍA Y EL TOTAL DE TODAS LAS 
	TONELADAS VENDIDAS.

*/

extern void exercise_30() {
	printf("\t\t***************************\n");
	printf("\t\t**      EJERCICIO 30     **\n");
	printf("\t\t***************************\n\n");
	
	
}
